export {
  VergeClient,
  type VergeClientOptions,
  type FetchLike,
  type JsonObject,
  type JsonValue,
  type BrowserInfo,
  type BrowserInfoResponse,
  type BrowserViewportRect,
  type BrowserViewportResponse,
  type ActiveWindowInfo,
  type SandboxResponse,
  type SandboxStatus,
  type SessionTicketResponse,
  type AccessTicketMode,
  type CdpInfoResponse,
  type CreateSandboxPayload,
  type UpdateSandboxPayload,
  type RequestErrorBody,
  type SessionUrlResponse,
  type ScreenshotFormat,
  type ScreenshotMetadata,
  type ScreenshotResponse,
  type ScreenshotType,
  type BrowserAction,
  type BrowserActionType,
  type BrowserActionsPayload,
  type BrowserActionsResponse,
  type MouseButton,
  type RestartBrowserPayload,
  type RestartBrowserResponse,
  type FileEntry,
  type ReadFileResponse,
  type WriteFilePayload,
  type WriteFileResponse,
  type UploadFilePayload,
  type UploadFileResponse,
  type DownloadFileResponse,
} from './client.js';

export {
  VergeError,
  VergeAuthError,
  VergeConfigError,
  VergeConflictError,
  VergeNotFoundError,
  VergeServerError,
  VergeValidationError,
} from './errors.js';
